services:
  transmission:
    image: ${TRANSMISSION_DOCKER_IMAGE:-'ghcr.io/linuxserver/transmission:latest'}
    restart: unless-stopped
    env_file:
      - ./env/linuxserver.env
      - ./env/transmission.default.env
      - ${TRANSMISSION_ENV_FILE:-./env/empty.env}
    environment:
      - LOCAL_NETWORK=${DOCKER_SUBNET:-172.50.0.0/24} # required for OpenVPN image
    cap_add:
      - net_admin
    dns:
      - ${TRAEFIK_IP_ADDRESS:-172.50.0.254}
    volumes:
      - ./data/transmission/config:/config
      - ${TRANSMISSION_DOWNLOAD_PATH:-./data/transmission/downloads}:/downloads
      - ${TRANSMISSION_WATCH_PATH:-./data/transmission/watch}:/watch
    labels:
      - traefik.enable=true
      - traefik.http.services.transmission.loadbalancer.server.port=9091
      - traefik.http.routers.transmission.entrypoints=web
      - traefik.http.routers.transmission.rule=Host(`transmission.${TAILSCALE_SEARCH_DOMAIN:-htpc.internal}`)
      - traefik.http.routers.transmission.service=transmission
      - traefik.tcp.services.transmission.loadbalancer.server.port=51413
      - traefik.tcp.routers.transmission.entrypoints=transmission
      - traefik.tcp.routers.transmission.rule=HostSNI(`*`)
      - traefik.tcp.routers.transmission.service=transmission
      - traefik.udp.services.transmission.loadbalancer.server.port=51413
      - traefik.udp.routers.transmission.entrypoints=transmissionudp
      - traefik.udp.routers.transmission.service=transmission

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    restart: unless-stopped
    env_file:
      - ./env/linuxserver.env
      - ${JACKETT_ENV_FILE:-./env/empty.env}
    dns:
      - ${TRAEFIK_IP_ADDRESS:-172.50.0.254}
    volumes:
      - ./data/jackett/config:/config
    labels:
      - traefik.enable=true
      - traefik.http.services.jackett.loadbalancer.server.port=9117
      - traefik.http.routers.jackett.entrypoints=web
      - traefik.http.routers.jackett.rule=Host(`jackett.${TAILSCALE_SEARCH_DOMAIN:-htpc.internal}`)
      - traefik.http.routers.jackett.service=jackett

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    env_file:
      - ./env/linuxserver.env
      - ${SONARR_ENV_FILE:-./env/empty.env}
    dns:
      - ${TRAEFIK_IP_ADDRESS:-172.50.0.254}
    volumes:
      - ./data/sonarr/config:/config
      - ${SONARR_TV_PATH:-./data/sonarr/tv}:/tv
      - ${TRANSMISSION_DOWNLOAD_PATH:-./data/transmission/downloads}:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.services.sonarr.loadbalancer.server.port=8989
      - traefik.http.routers.sonarr.entrypoints=web
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${TAILSCALE_SEARCH_DOMAIN:-htpc.internal}`)
      - traefik.http.routers.sonarr.service=sonarr

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    env_file:
      - ./env/linuxserver.env
      - ${RADARR_ENV_FILE:-./env/empty.env}
    dns:
      - ${TRAEFIK_IP_ADDRESS:-172.50.0.254}
    volumes:
      - ./data/radarr/config:/config
      - ${RADARR_MOVIES_PATH:-./data/radarr/movies}:/movies
      - ${TRANSMISSION_DOWNLOAD_PATH:-./data/transmission/downloads}:/downloads
    labels:
      - traefik.enable=true
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - traefik.http.routers.radarr.entrypoints=web
      - traefik.http.routers.radarr.rule=Host(`radarr.${TAILSCALE_SEARCH_DOMAIN:-htpc.internal}`)
      - traefik.http.routers.radarr.service=radarr

  overseerr:
    image: ghcr.io/linuxserver/overseerr:latest
    restart: unless-stopped
    env_file:
      - ./env/linuxserver.env
      - ${OVERSEERR_ENV_FILE:-./env/empty.env}
    dns:
      - ${TRAEFIK_IP_ADDRESS:-172.50.0.254}
    volumes:
      - ./data/overseerr/config:/config
    labels:
      - traefik.enable=true
      - traefik.http.services.overseerr.loadbalancer.server.port=5055
      - traefik.http.routers.overseerr.entrypoints=web
      - traefik.http.routers.overseerr.rule=Host(`overseerr.${TAILSCALE_SEARCH_DOMAIN:-htpc.internal}`)
      - traefik.http.routers.overseerr.service=overseerr

  tailscale:
    image: fastandfearless/tailscale:fromsource-amd64-v1.10.2-c24cbde
    restart: unless-stopped
    command:
      - sh
      - -c
      - |
        set -e

        # Create the tun device path if required
        if [ ! -d /dev/net ]; then mkdir /dev/net; fi
        if [ ! -e /dev/net/tun ]; then mknod /dev/net/tun c 10 200; fi

        exec tailscaled --state=/var/run/tailscale/tailscale.state
    env_file:
      - ${TAILSCALE_ENV_FILE:-./env/empty.env}
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    cap_add:
      - net_admin
    volumes:
      - ./data/tailscale/config:/var/run/tailscale

  coredns:
    image: coredns/coredns:latest
    restart: unless-stopped
    command:
      - -conf=/var/run/coredns/Corefile
    env_file:
      - ${COREDNS_ENV_FILE:-./env/empty.env}
    environment:
      - TAILSCALE_SEARCH_DOMAIN=${TAILSCALE_SEARCH_DOMAIN:-htpc.internal}
      - TRAEFIK_IP_ADDRESS=${TRAEFIK_IP_ADDRESS:-172.50.0.254}
    volumes:
      - ./data/coredns/config:/var/run/coredns
    labels:
      - traefik.enable=true
      - traefik.udp.services.coredns.loadbalancer.server.port=53
      - traefik.udp.routers.coredns.entrypoints=coredns
      - traefik.udp.routers.coredns.service=coredns

  traefik:
    image: traefik:2.4
    restart: unless-stopped
    command:
      - --accesslog.format=json
      - --api.insecure=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.coredns.address=:53/udp
      - --entrypoints.transmission.address=:51413
      - --entrypoints.transmissionudp.address=:51413/udp
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.exposedbydefault=false
    env_file:
      - ${TRAEFIK_ENV_FILE:-./env/empty.env}
    expose:
      - 80
      - 53/udp
      - 51413
      - 51413/udp
    ports:
      - ${TRAEFIK_HTTP_PORT:-80}:80
      - ${TRAEFIK_COREDNS_PORT:-53}:53/udp
      - ${TRAEFIK_TRANSMISSION_PORT:-51413}:51413
      - ${TRAEFIK_TRANSMISSION_PORT:-51413}:51413/udp
    networks:
      default:
        ipv4_address: ${TRAEFIK_IP_ADDRESS:-172.50.0.254}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    cap_drop:
      - all
    cap_add:
      - net_bind_service
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.${TAILSCALE_SEARCH_DOMAIN:-htpc.internal}`)
      - traefik.http.routers.traefik.entrypoints=web
      - traefik.http.routers.traefik.service=api@internal

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_SUBNET:-172.50.0.0/24}
